### ISSUE TITLE
ArchLinux下运行错误

### ISSUE THREAD

**Issue by zxp19821005** [singcl/XmVideoPlayer#2]
如题。
我将该软件移植到了ArchLinux的AUR： [xm-video-player-bin](https://aur.archlinux.org/packages/xm-video-player-bin)，今天在更新软件包时，出现了错误。
### 环境信息
OS：EndeavourOS
Kernel: 6.1.61-1-lts
软件版本： [0.4.15](https://github.com/singcl/XmVideoPlayer/releases/tag/v0.4.15)
桌面环境： cinnamon 5.8.4
gstreamer: 1.22.6

### 报错信息
软件运行后，界面任何按钮点击无效，第二次运行后直接黑屏。
在终端中运行，出现报错信息，如下：
```
$ xm-video-player
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:100610): GLib-GObject-CRITICAL **: 09:54:03.581: invalid (NULL) pointer instance

(WebKitWebProcess:100610): GLib-GObject-CRITICAL **: 09:54:03.581: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
不知道是我的gstreamer版本太高，还是需要安装其他的gstreamer组件？

**Comment by singcl** [comment]
> 如题。 我将该软件移植到了ArchLinux的AUR： [xm-video-player-bin](https://aur.archlinux.org/packages/xm-video-player-bin)，今天在更新软件包时，出现了错误。
> 
> ### 环境信息
> OS：EndeavourOS Kernel: 6.1.61-1-lts 软件版本： [0.4.15](https://github.com/singcl/XmVideoPlayer/releases/tag/v0.4.15) 桌面环境： cinnamon 5.8.4 gstreamer: 1.22.6
> 
> ### 报错信息
> 软件运行后，界面任何按钮点击无效，第二次运行后直接黑屏。 在终端中运行，出现报错信息，如下：
> 
> ```
> $ xm-video-player
> GStreamer element autoaudiosink not found. Please install it
> 
> (WebKitWebProcess:100610): GLib-GObject-CRITICAL **: 09:54:03.581: invalid (NULL) pointer instance
> 
> (WebKitWebProcess:100610): GLib-GObject-CRITICAL **: 09:54:03.581: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> ```
> 
> 不知道是我的gstreamer版本太高，还是需要安装其他的gstreamer组件？

v0.4.15之前的版本能正常运行吗？我暂时没有linux环境来验证这个问题。在windows和macos上目前不会出现这一问题。如果有合适条件我会验证这个问题。v0.4.15只是更新了一个列表链接可以复制的功能，不算太重要的一个小功能。如果之前的版本可以的话，我建议安装之前的版本。(#`O′)

**Comment by zxp19821005** [comment]
在0.5.1版本下依然报这个错误，可能是我运行环境的问题，但是目前已经可以正常运行了。
